In [ ]:
print("my name is Ankush")

my name is Ankush

In [ ]:
import pandas as pd
df = pd.read_csv("salaries_by_college_major.csv")

In [ ]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
df.shape

(51, 6)

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [ ]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [ ]:
clean_df = df.dropna()

In [ ]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df = clean_df

In [ ]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
df["Undergraduate Major"]

0                               Accounting
1                    Aerospace Engineering
2                              Agriculture
3                             Anthropology
4                             Architecture
5                              Art History
6                                  Biology
7                      Business Management
8                     Chemical Engineering
9                                Chemistry
10                       Civil Engineering
11                          Communications
12                    Computer Engineering
13                        Computer Science
14                            Construction
15                        Criminal Justice
16                                   Drama
17                               Economics
18                               Education
19                  Electrical Engineering
20                                 English
21                                    Film
22                                 Finance
23                                Forestry
24                               Geography
25                                 Geology
26                          Graphic Design
27              Health Care Administration
28                                 History
29                   Hospitality & Tourism
30                  Industrial Engineering
31             Information Technology (IT)
32                         Interior Design
33                 International Relations
34                              Journalism
35    Management Information Systems (MIS)
36                               Marketing
37                                    Math
38                  Mechanical Engineering
39                                   Music
40                                 Nursing
41                               Nutrition
42                              Philosophy
43                     Physician Assistant
44                                 Physics
45                       Political Science
46                              Psychology
47                                Religion
48                               Sociology
49                                 Spanish
Name: Undergraduate Major, dtype: object

In [ ]:
df["Undergraduate Major"].max()

'Spanish'

In [ ]:
df["Starting Median Salary"].max()

74300.0

In [ ]:
df["Starting Median Salary"].idxmax()

43

In [ ]:
df["Starting Median Salary"].loc(43)

ValueError: No axis named 43 for object type Series

In [ ]:
df["Starting Median Salary"][43]

74300.0

In [ ]:
df.loc(43)

ValueError: No axis named 43 for object type DataFrame

In [ ]:
df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df["Undergraduate Major"].loc[df["Starting Median Salary"].idxmin()]

'Spanish'

In [1]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

NameError: name 'clean_df' is not defined

In [2]:
df['Mid-Career 90th Percentile Salary'].subtract(df['Mid-Career 10th Percentile Salary'])

NameError: name 'df' is not defined

In [3]:
import pandas as pd
df = pd.read_csv("salaries_by_college_major.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'salaries_by_college_major.csv'

In [4]:
df = pd.read_csv("salaries_by_college_major.csv")

In [5]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [6]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

NameError: name 'clean_df' is not defined

In [7]:
df['Mid-Career 90th Percentile Salary'].subtract(df['Mid-Career 10th Percentile Salary'])

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
50         NaN
dtype: float64

In [8]:
df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [9]:
df.dropna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [10]:
new_column = df["Mid-Career 10th Percentile Salary"].subtract(["Mid-Career 90th Percentile Salary"])
df.insert(1,"spread",new_column)

ValueError: Lengths must be equal

In [11]:
new_column = df["Mid-Career 10th Percentile Salary"]-["Mid-Career 90th Percentile Salary"]
df.insert(1,"spread",new_column)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('float64'), dtype('<U33')) -> None

In [12]:
new_column = df["Mid-Career 10th Percentile Salary"].subtract(df["Mid-Career 90th Percentile Salary"])
df.insert(1,"spread",new_column)

In [13]:
df.head()

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,-109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,-96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,-113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,-104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,-85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [14]:
df.drop("spread", axis=1)

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [15]:
new_column = df["Mid-Career 90th Percentile Salary"].subtract(df["Mid-Career 10th Percentile Salary"])
df.insert(1,"spread",new_column)

ValueError: cannot insert spread, already exists

In [16]:
df

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,-109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,-96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,-113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,-104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,-85400.0,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,-96200.0,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,-98100.0,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,-108200.0,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,-122100.0,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,-102700.0,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,-84600.0,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,-105500.0,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,-95900.0,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,-98000.0,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,-114700.0,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,-74800.0,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,-116300.0,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,-159400.0,50100.0,98600.0,50600.0,210000.0,Business
18,Education,-72700.0,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,-98700.0,60900.0,103000.0,69300.0,168000.0,STEM
20,English,-99600.0,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,-102100.0,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,-147800.0,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,-70000.0,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,-92000.0,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,-111000.0,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,-76000.0,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,-66400.0,38800.0,60600.0,34600.0,101000.0,Business
28,History,-112000.0,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,-88500.0,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,-115900.0,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),-84500.0,49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,-71300.0,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,-118800.0,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,-106600.0,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),-100700.0,49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,-132900.0,40800.0,79600.0,42100.0,175000.0,Business
37,Math,-137800.0,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,-99300.0,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,-107300.0,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,-50700.0,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,-65300.0,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,-132500.0,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,-57600.0,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,-122000.0,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,-126800.0,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,-95400.0,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,-66700.0,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,-87300.0,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,-65400.0,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df = df.drop("spread", axis=1)

In [18]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [19]:
new_column = df["Mid-Career 90th Percentile Salary"].subtract(["Mid-Career 10th Percentile Salary"])
df.insert(1,"spread",new_column)

ValueError: Lengths must be equal

In [20]:
df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [21]:
df = df.dropna()

In [22]:
df

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,50100.0,98600.0,50600.0,210000.0,Business
18,Education,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,60900.0,103000.0,69300.0,168000.0,STEM
20,English,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,38800.0,60600.0,34600.0,101000.0,Business
28,History,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,40800.0,79600.0,42100.0,175000.0,Business
37,Math,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [23]:
new_column = df["Mid-Career 90th Percentile Salary"].subtract(df["Mid-Career 10th Percentile Salary"])
df.insert(1,"spread",new_column)

In [24]:
df.head()

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [25]:
df

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
5,Art History,96200.0,35800.0,64900.0,28800.0,125000.0,HASS
6,Biology,98100.0,38800.0,64800.0,36900.0,135000.0,STEM
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
11,Communications,105500.0,38100.0,70000.0,37500.0,143000.0,HASS
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
15,Criminal Justice,74800.0,35000.0,56300.0,32200.0,107000.0,HASS
16,Drama,116300.0,35900.0,56900.0,36700.0,153000.0,HASS
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business
18,Education,72700.0,34900.0,52000.0,29300.0,102000.0,HASS
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
20,English,99600.0,38000.0,64700.0,33400.0,133000.0,HASS
21,Film,102100.0,37900.0,68500.0,33900.0,136000.0,HASS
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
23,Forestry,70000.0,39100.0,62600.0,41000.0,111000.0,Business
24,Geography,92000.0,41200.0,65500.0,40000.0,132000.0,HASS
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
26,Graphic Design,76000.0,35700.0,59800.0,36000.0,112000.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business
28,History,112000.0,39200.0,71000.0,37000.0,149000.0,HASS
29,Hospitality & Tourism,88500.0,37800.0,57500.0,35500.0,124000.0,Business
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
32,Interior Design,71300.0,36100.0,53200.0,35700.0,107000.0,HASS
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
34,Journalism,106600.0,35600.0,66700.0,38400.0,145000.0,HASS
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
39,Music,107300.0,35900.0,55000.0,26700.0,134000.0,HASS
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS

In [26]:
array = df.sort_values("spread")

In [27]:
array

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
23,Forestry,70000.0,39100.0,62600.0,41000.0,111000.0,Business
32,Interior Design,71300.0,36100.0,53200.0,35700.0,107000.0,HASS
18,Education,72700.0,34900.0,52000.0,29300.0,102000.0,HASS
15,Criminal Justice,74800.0,35000.0,56300.0,32200.0,107000.0,HASS
26,Graphic Design,76000.0,35700.0,59800.0,36000.0,112000.0,HASS
31,Information Technology (IT),84500.0,49100.0,74800.0,44500.0,129000.0,STEM
10,Civil Engineering,84600.0,53900.0,90500.0,63400.0,148000.0,STEM
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
29,Hospitality & Tourism,88500.0,37800.0,57500.0,35500.0,124000.0,Business
24,Geography,92000.0,41200.0,65500.0,40000.0,132000.0,HASS
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
12,Computer Engineering,95900.0,61400.0,105000.0,66100.0,162000.0,STEM
5,Art History,96200.0,35800.0,64900.0,28800.0,125000.0,HASS
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
13,Computer Science,98000.0,55900.0,95500.0,56000.0,154000.0,STEM
6,Biology,98100.0,38800.0,64800.0,36900.0,135000.0,STEM
19,Electrical Engineering,98700.0,60900.0,103000.0,69300.0,168000.0,STEM
38,Mechanical Engineering,99300.0,57900.0,93600.0,63700.0,163000.0,STEM
20,English,99600.0,38000.0,64700.0,33400.0,133000.0,HASS
35,Management Information Systems (MIS),100700.0,49200.0,82300.0,45300.0,146000.0,STEM
21,Film,102100.0,37900.0,68500.0,33900.0,136000.0,HASS
9,Chemistry,102700.0,42600.0,79900.0,45300.0,148000.0,STEM
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
11,Communications,105500.0,38100.0,70000.0,37500.0,143000.0,HASS
34,Journalism,106600.0,35600.0,66700.0,38400.0,145000.0,HASS
39,Music,107300.0,35900.0,55000.0,26700.0,134000.0,HASS
7,Business Management,108200.0,43000.0,72100.0,38800.0,147000.0,Business
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
25,Geology,111000.0,43500.0,79500.0,45000.0,156000.0,STEM
28,History,112000.0,39200.0,71000.0,37000.0,149000.0,HASS
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
14,Construction,114700.0,53700.0,88900.0,56300.0,171000.0,Business
30,Industrial Engineering,115900.0,57700.0,94700.0,57100.0,173000.0,STEM
16,Drama,116300.0,35900.0,56900.0,36700.0,153000.0,HASS
33,International Relations,118800.0,40900.0,80900.0,38200.0,157000.0,HASS
44,Physics,122000.0,50300.0,97300.0,56000.0,178000.0,STEM
8,Chemical Engineering,122100.0,63200.0,107000.0,71900.0,194000.0,STEM
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
42,Philosophy,132500.0,39900.0,81200.0,35500.0,168000.0,HASS
36,Marketing,132900.0,40800.0,79600.0,42100.0,175000.0,Business
37,Math,137800.0,45400.0,92400.0,45200.0,183000.0,STEM
22,Finance,147800.0,47900.0,88300.0,47200.0,195000.0,Business
17,Economics,159400.0,50100.0,98600.0,50600.0,210000.0,Business

In [28]:
array.head()

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
40,Nursing,50700.0,54200.0,67000.0,47600.0,98300.0,Business
43,Physician Assistant,57600.0,74300.0,91700.0,66400.0,124000.0,STEM
41,Nutrition,65300.0,39900.0,55300.0,33900.0,99200.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS
27,Health Care Administration,66400.0,38800.0,60600.0,34600.0,101000.0,Business

In [29]:
df.tail()

,Undergraduate Major,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,126800.0,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,95400.0,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,66700.0,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,87300.0,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,65400.0,34000.0,53100.0,31000.0,96400.0,HASS